name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up compiler
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt -y install gcc-13

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
    
    - name: Set up Conan profile
      run: conan profile detect

    - name: Build
      run: conan build . -o test=True -s build_type=Debug --build=missing

    - name: Test Package
      run: conan test test_package repr/0.1

    - name: Test
      run: ./build/Debug/repr_test
