name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Build
      run: conan build . -o test=True -s build_type=Debug --build=missing

    - name: Test Package
      run: conan test test_package repr/0.1

    - name: Test
      run: ./build/Debug/repr_test
